name: Deploy Reasoning Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Or your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dependencies/requirements.txt

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # Replace with your workload identity provider
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com' # Replace with your service account

    - name: Deploy to Vertex AI
      run: |
        python build/deploy.py --requirements=requirements.txt --extra_packages=app
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }} # Use GitHub secrets for sensitive info
        LOCATION: ${{ secrets.LOCATION }}
        STAGING_BUCKET: ${{ secrets.STAGING_BUCKET }}
